spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers: PLAINTEXT://kafka-broker:9092
spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.streams.binder.brokers: PLAINTEXT://kafka-broker:9092
spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes: zookeeper:2181
spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.streams.binder.zkNodes: zookeeper:2181
spring.cloud.skipper.client.serverUri: http://localhost:7577/api